export interface Lesson {
  id: number;
  title: string;
  body: string;
  subject_id: number;
  section_one: string;
  example_one: string;
  example_one_explanation: string;
  section_two: string;
  example_two: string;
  example_two_explanation: string;
  section_three: string;
  example_three: string;
  example_three_explanation: string;
  section_four: string;
  example_four: string;
  example_four_explanation: string;
  section_five: string;
  example_five: string;
  example_five_explanation: string;
  section_six: string;
  example_six: string;
  example_six_explanation: string;
  section_seven: string;
  example_seven: string;
  example_seven_explanation: string;
  section_eight: string;
  example_eight: string;
  example_eight_explanation: string;
  section_nine: string
  example_nine: string;
  example_nine_explanation: string;
  section_ten: string;
  example_ten: string;
  example_ten_explanation: string;
  created_at: string;
  updated_at: string;
}